### ISSUE TITLE
Tablero de hitos/Sprint

### ISSUE THREAD

**Issue by mbm0089** [albartolome/Arduino#10]
@clopzeno solicita tablero de hitos/Sprint

**Comment by albartolome** [comment]
En nuesto caso, los hitos son los que se ponían como duración 0 en el diagrama de Gantt. Es decir el final de las épicas  #7 y #1

**Comment by mbm0089** [comment]
![screen shot 2016-11-06 at 10 47 10](https://cloud.githubusercontent.com/assets/23175380/20036658/678ef3d0-a40e-11e6-9cd8-a3dd9c67f3d7.png)
