### ISSUE TITLE
Una evidencia de que se ha trabajado de manera sincronizada

### ISSUE THREAD

**Issue by albartolome** [albartolome/Arduino#12]
¿ @mbm0089 podrias dar una prueba de que se ha trabajado de forma sincronizada?

**Comment by mbm0089** [comment]
Creo que: 
![screen shot 2016-11-03 at 19 12 18](https://cloud.githubusercontent.com/assets/23175380/20036697/a6359c82-a40f-11e6-8df2-199b2fe2ec55.png)
o
![screen shot 2016-11-03 at 19 10 56](https://cloud.githubusercontent.com/assets/23175380/20036699/b7014a16-a40f-11e6-8a8d-19f807222d5b.png)

Podría servir como prueba
