### ISSUE TITLE
Sprint.1

### ISSUE THREAD

**Issue by mbm0089** [albartolome/Arduino#15]
Deberíamos modificar el tiempo de finalización del milestone Finalización descrito en issue #7  ??

**Comment by albartolome** [comment]
Si, quizá podriamos adelantarlo un poco.

**Comment by albartolome** [comment]
Acabo de adelantar el tiempo del milestone "Finalización" que esta en el issue #7 . Lo adelante tan solo un dia, ahora esta configurado para que acabe el lunes 7 de noviembre.
